### ISSUE TITLE
Invalid scss in bulma preset

### ISSUE THREAD

**Issue by Johannestegner** [roots/sage-installer#31]
The bulma preset have a include in the `_wp-classes.scss` which is invalid in SCSS. I suspect that `node-sass` accepts it and will compile it correctly, while the recommended package `sass` (dart implementation) is more strict and will throw an error upon reaching this line.

The following is the line:

https://github.com/roots/sage-installer/blob/60c329d6f5d750f78804b9577f2944c05b3a24dc/src/Presets/stubs/Bulma/styles/components/_wp-classes.scss#L26

The `+tablet()` sass call is equal to (when using scss) `@include tablet()`, changing to this will allow `dart-sass` to compile the code successfully.

**Comment by mmirus** [comment]
Thanks for reporting!

**Comment by Log1x** [comment]
Not even sure `node-sass` would've compiled this without it being a `.sass` extension.

**Comment by jgthms** [comment]
I’m not responsible for this Bulma. It has nothing to do with my CSS framework.

**Comment by Log1x** [comment]
@jgthms – it has nothing to do with this include. I meant more-so in general, an organized SCSS rewrite would be nice and I'd imagine more maintainable. Either way, sorry to highlight you. Wasn't meant to be taken out of context.
